#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
        purge)
                # Remove the configuration data.
                #/etc/init.d/couchpotato stop &>/dev/null

                rm -Rf /opt/couchpotato/* &>/dev/null
                #omv_config_delete "//services/couchpotato"

                if [ -f "/var/run/couchpotato/couchpotato.pid" ]; then
                        PID=$(cat /var/run/couchpotato/couchpotato.pid);
                        kill -0 $PID 2>/dev/null;
                        if [ $? -eq 0 ]; then
                                kill -9 $PID;
                                rm -Rf /var/run/couchpotato
                        fi
                fi
                omv_config_delete "//services/couchpotato"
                #if [ -f "/etc/init.d/couchpotato" ]; then
                #       rm /etc/init.d/couchpotato &>/dev/null
                #fi
                #if [ -d "/opt/couchpotato" ]; then
                #       rm -Rf /opt/couchpotato/* &>/dev/null
                #fi
                #if [ -d "/home/couchpotato/.couchpotato" ]; then
                #       rm -Rf /home/couchpotato/.couchpotato &>/dev/null
                #fi
                #invoke-rc.d --force couchpotato stop
                #update-rc.d couchpotato remove &>/dev/null
                #rm /opt/couchpotato/* -Rf
                userdel -r couchpotato
        ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0