#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! getent passwd couchpotato >/dev/null 2>&1; then
            echo "Adding couchpotato user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin couchpotato
            insserv -d couchpotato
        else
            echo "couchpotato user already exists."
        fi

        if [ -e /var/run/couchpotato ]; then
            echo "Cleaning old pid file..."
            rm -Rf /var/run/couchpotato
        fi

        chmod 775 /opt
        chown root:users /opt

        if ! omv_config_exists "/config/services/couchpotato"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
            object="${object}<showtab>0</showtab>"
            object="${object}<branch></branch>"
            object="${object}<repo></repo>"
            omv_config_add_element "/config/services" "couchpotato" "${object}" true
        fi
        
        #Check for new omv_config options
        if ! omv_config_exists "/config/services/couchpotato/port"; then
            echo "Extra configuration."
            object="<port>5050</port>"
            object="${object}<mntentref></mntentref>"
            object="${object}<path></path>"
            object="${object}<forks></forks>"
            omv_config_add_element "/config/services" "couchpotato" "${object}" true
        fi
		
        omv_install_fixperms

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0