#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COUCHPOTATO_APP_PATH="/opt/couchpotato/"
OMV_COUCHPOTATO_DATA_PATH="/var/opt/couchpotato"
OMV_COUCHPOTATO_XPATH="/config/services/couchpotato"

case "$1" in
    purge)
        omv_config_delete $OMV_COUCHPOTATO_XPATH

        if [ -d $OMV_COUCHPOTATO_APP_PATH ]; then
            find $OMV_COUCHPOTATO_APP_PATH -mindepth 1 -delete
        fi

        if [ -d $OMV_COUCHPOTATO_DATA_PATH ]; then
            find $OMV_COUCHPOTATO_DATA_PATH -mindepth 1 -delete
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
