#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        rm -Rf /opt/couchpotato & >/dev/null

        if [ -f "/var/run/couchpotato/couchpotato.pid" ]; then
            PID=$(cat /var/run/couchpotato/couchpotato.pid);
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
                rm -Rf /var/run/couchpotato
            fi
        fi

        omv_config_delete "//services/couchpotato"

        if [ -d "/opt/couchpotato" ]; then
            rm -Rf /opt/couchpotato/* &>/dev/null
            rm -Rf /opt/couchpotato/.git &>/dev/null
            rm -Rf /opt/couchpotato/.gitignore
        fi

        userdel -r couchpotato

        if [ ! -d /opt ]; then
            mkdir /opt
            chmod 775 /opt
        fi
    ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0