#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! grep -q "^couchpotato:" /etc/passwd; then
            echo "Adding couchpotato user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin couchpotato
        else
            echo "couchpotato user already exists."
        fi

        if [ -e /var/run/couchpotato ]; then
            echo "Cleaning old pid file..."
            rm /var/run/couchpotato -Rf
        fi

        chmod 775 /opt
        chown root:users /opt

        if ! omv_config_exists "/config/services/couchpotato"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
            object="${object}<showtab>0</showtab>"
            object="${object}<cp_branch>0</cp_branch>"
            object="${object}<cp_repo></cp_repo>"
            omv_config_add_element "/config/services" "couchpotato" "${object}" true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
